# Generated by Django 6.0.8 on 2026-08-05 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(max_length=60)),
                ('entity', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(default='OM', max_length=2)),
                ('timezone', models.CharField(default='Asia/Muscat', max_length=40)),
                ('base_currency', models.CharField(default='OMR', max_length=3)),
                ('fx_rate_usd', models.DecimalField(decimal_places=4, default='0.3850', max_digits=8)),
                ('language_mode', models.CharField(default='EN_AR_BILINGUAL', max_length=20)),
                ('mfa_enforced', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('admin_alerts', models.BooleanField(default=True)),
                ('allow_user_logins', models.BooleanField(default=True)),
                ('backup_retention_years', models.PositiveSmallIntegerField(default=7)),
                ('maintenance_window', models.CharField(default='Sun 02:00-04:00 GST', max_length=40)),
                ('webhook_url', models.URLField(blank=True)),
                ('admin_alert_contact', models.CharField(blank=True, max_length=120)),
                ('master_api_key', models.CharField(blank=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
