# Generated by Django 6.0.8 on 2026-08-05 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line_id', models.PositiveSmallIntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_code', models.CharField(default='EA', max_length=6)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('vat_category', models.CharField(choices=[('S', 'Standard 5%'), ('Z', 'Zero'), ('E', 'Exempt')], default='S', max_length=2)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('line_net', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['line_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('AR', 'AR / Sales'), ('AP', 'AP / Purchase')], max_length=2)),
                ('doc_type', models.CharField(choices=[('380', 'Standard Tax Invoice'), ('381', 'Credit Note'), ('383', 'Debit Note'), ('389', 'Self-Billed Invoice'), ('261', 'Self-Billed Credit Note')], default='380', max_length=3)),
                ('is_b2c', models.BooleanField(default=False)),
                ('is_export', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(max_length=40)),
                ('uuid_v5', models.UUIDField(blank=True, null=True)),
                ('transaction_type_code', models.CharField(default='10000000000000000000', max_length=20)),
                ('issue_date', models.DateField()),
                ('issue_time', models.TimeField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tax_point_date', models.DateField(blank=True, null=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=200)),
                ('counterparty_vatin', models.CharField(blank=True, max_length=14)),
                ('counterparty_endpoint', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='OMR', max_length=3)),
                ('line_extension_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('allowance_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('charge_total', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_exclusive_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tax_inclusive_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('payable_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('payment_means_code', models.CharField(choices=[('10', 'Cash'), ('30', 'Credit Transfer')], default='30', max_length=3)),
                ('payment_iban', models.CharField(blank=True, max_length=34)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('SENT', 'Sent'), ('REPORTED', 'Reported'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('REST_API', 'REST API'), ('BATCH', 'File Upload'), ('SFTP', 'SFTP Sync'), ('ERP', 'ERP Integration'), ('AP_INBOUND', 'AP Inbound REST API')], default='MANUAL', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ap_status', models.CharField(blank=True, max_length=40)),
                ('erp_system', models.CharField(blank=True, max_length=40)),
                ('billing_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='documents.document')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
