# Generated by Django 6.0.8 on 2026-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('STANDARD_380', 'Standard Tax Invoice'), ('SIMPLIFIED_B2C', 'Simplified Tax Invoice'), ('CREDIT_NOTE_381', 'Credit Note'), ('DEBIT_NOTE_383', 'Debit Note'), ('SELF_BILLED_389', 'Self-Billed Invoice'), ('SELF_BILLED_CN_261', 'Self-Billed Credit Note')], default='STANDARD_380', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
