# Generated by Django 6.0.8 on 2026-08-05 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('short_code', models.CharField(blank=True, max_length=4)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('cr_number', models.CharField(max_length=20, unique=True)),
                ('vat_number', models.CharField(max_length=14, unique=True)),
                ('peppol_participant_id', models.CharField(max_length=30)),
                ('entity_type', models.CharField(choices=[('HQ', 'HQ'), ('SUBSIDIARY', 'Subsidiary'), ('BRANCH', 'Branch')], default='HQ', max_length=12)),
                ('branch_id_code', models.CharField(default='0000', max_length=4)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=12)),
                ('invoice_suffix', models.CharField(default='/OM', max_length=8)),
                ('credit_note_suffix', models.CharField(default='/CN', max_length=8)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('prefixes', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Muscat', max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country_code', models.CharField(default='OM', max_length=2)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['short_code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('group_vatin', models.CharField(max_length=14)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('vatin', models.CharField(blank=True, max_length=14)),
                ('peppol_endpoint', models.CharField(blank=True, max_length=30)),
                ('is_walkin', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country_code', models.CharField(default='OM', max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
