# Generated by Django 6.0.8 on 2026-08-05 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Schematron OK'), ('AS4_SENT', 'AS4 Sent (C2→C3)'), ('ACK_RECEIVED', 'Ack Received'), ('TDD_REPORTED', 'TDD Reported (C5)'), ('MLS_RECEIVED', 'MLS Received'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=14)),
                ('payload', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('ota_response_code', models.CharField(blank=True, max_length=10)),
                ('ota_message', models.CharField(blank=True, max_length=255)),
                ('mls_status', models.CharField(blank=True, max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.company')),
            ],
            options={
                'ordering': ['-attempt', '-created_at'],
                'abstract': False,
            },
        ),
    ]
